package home.shared.hibernate;
// Generated 09.07.2009 10:42:43 by Hibernate Tools 3.2.1.GA



/**
 * AccountConnector generated by hbm2java
 */
public class AccountConnector  implements java.io.Serializable {


     private int id;
     private Mandant mandant;
     private String type;
     private String ip;
     private Integer port;
     private String username;
     private String pwd;
     private int flags;


    public AccountConnector() {
    }

	
    public AccountConnector(int id) {
        this.id = id;
    }

    public AccountConnector( int id, Mandant mandant, String type, String ip, Integer port, String user, String pwd, int flags )
    {
        this.id = id;
        this.mandant = mandant;
        this.type = type;
        this.ip = ip;
        this.port = port;
        this.username = user;
        this.pwd = pwd;
        this.flags = flags;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mandant getMandant() {
        return this.mandant;
    }
    
    public void setMandant(Mandant mandant) {
        this.mandant = mandant;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Integer getPort() {
        return this.port;
    }
    
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * @return the user
     */
    public String getUsername()
    {
        return username;
    }

    /**
     * @param user the user to set
     */
    public void setUsername( String user )
    {
        this.username = user;
    }

    /**
     * @return the pwd
     */
    public String getPwd()
    {
        return pwd;
    }

    /**
     * @param pwd the pwd to set
     */
    public void setPwd( String pwd )
    {
        this.pwd = pwd;
    }

    /**
     * @return the flags
     */
    public int getFlags()
    {
        return flags;
    }

    /**
     * @param flags the flags to set
     */
    public void setFlags( int flags )
    {
        this.flags = flags;
    }




}


