package home.shared.hibernate;
// Generated 09.07.2009 10:42:43 by Hibernate Tools 3.2.1.GA




/**
 * AccountConnector generated by hbm2java
 */
public class MailAddLink  implements java.io.Serializable {



     private int muId;
     private int maId;


    public MailAddLink() {
    }

	
    public MailAddLink(int mu_id, int ma_id)
    {
        this.muId = mu_id;
        this.maId = ma_id;
    }

    /**
     * @return the muId
     */
    public int getMuId()
    {
        return muId;
    }

    /**
     * @param muId the muId to set
     */
    public void setMuId( int muId )
    {
        this.muId = muId;
    }

    /**
     * @return the maId
     */
    public int getMaId()
    {
        return maId;
    }

    /**
     * @param maId the maId to set
     */
    public void setMaId( int maId )
    {
        this.maId = maId;
    }

   
  


}


