/*
 * ZipStatusDlg.java
 *
 * Created on 26. Januar 2009, 16:58
 */

package home.shared.Utilities;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 
 @author  Administrator
 */
public class ZipStatusDlg extends javax.swing.JDialog implements ZipListener, ActionListener
{
    StringBuffer sb;
    ZipUtilities zu;
    
    String last_status;
    int last_code = -1;
    
    boolean finished;
    int auto_close_cnt;
    
    /** Creates new form ZipStatusDlg */
    public ZipStatusDlg(java.awt.Frame parent, ZipUtilities _zu)
    {
        super(parent, true);
        initComponents();
        zu = _zu;
        
        if (zu == null)
        {
            BT_ACTION.setEnabled(false);
        }
        finished = false;
        sb = new StringBuffer("initializing...\n");
        
        zu.addListener(this);
    }

    public void call_auto_close()
    {
        Timer timer = new Timer( 1000, this);
        auto_close_cnt = 3;
        timer.start();
    }

    public boolean is_finished()
    {
        return finished;
    }


    
    
    /** This method is called from within the constructor to
     initialize the form.
     WARNING: Do NOT modify this code. The content of this method is
     always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PB_PERCENT = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        TXTA_TERMINAL = new javax.swing.JTextArea();
        BT_ACTION = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        PB_FILE_PERCENT = new javax.swing.JProgressBar();
        TXT_FILENAME = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TXTA_DESCRIPTION = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TXTA_TERMINAL.setColumns(20);
        TXTA_TERMINAL.setEditable(false);
        TXTA_TERMINAL.setRows(5);
        jScrollPane1.setViewportView(TXTA_TERMINAL);

        BT_ACTION.setText("Abort"); // NOI18N
        BT_ACTION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ACTIONActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 124, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 27, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 124, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 27, Short.MAX_VALUE)
        );

        TXT_FILENAME.setEditable(false);

        jScrollPane2.setBorder(null);

        TXTA_DESCRIPTION.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.background"));
        TXTA_DESCRIPTION.setColumns(20);
        TXTA_DESCRIPTION.setEditable(false);
        TXTA_DESCRIPTION.setRows(5);
        jScrollPane2.setViewportView(TXTA_DESCRIPTION);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(BT_ACTION)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jSeparator2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PB_PERCENT, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(TXT_FILENAME, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(PB_FILE_PERCENT, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(PB_FILE_PERCENT, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(TXT_FILENAME, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PB_PERCENT, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(BT_ACTION)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_ACTIONActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BT_ACTIONActionPerformed
    {//GEN-HEADEREND:event_BT_ACTIONActionPerformed
        // TODO add your handling code here:
        if ((zu != null && zu.is_aborted()) || last_code == ZipListener.ST_READY)
        {
            this.setVisible(false);
            finished = true;
        }
        else
        {
            new_status(ZipListener.ST_ERROR, "Aborting...");
            
            if (zu != null)
                zu.do_abort();
        }
    }//GEN-LAST:event_BT_ACTIONActionPerformed
    
    /**
     @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            
            public void run()
            {
                ZipStatusDlg dialog = new ZipStatusDlg(new javax.swing.JFrame(), null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_ACTION;
    private javax.swing.JProgressBar PB_FILE_PERCENT;
    private javax.swing.JProgressBar PB_PERCENT;
    private javax.swing.JTextArea TXTA_DESCRIPTION;
    private javax.swing.JTextArea TXTA_TERMINAL;
    private javax.swing.JTextField TXT_FILENAME;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables

  
    public void act_file_name(String name)
    {
        TXT_FILENAME.setText(name);
        
    }

   
    public void total_percent(int pc)
    {
        PB_PERCENT.setValue(pc);
    }

    
    public void file_percent(int pc)
    {
        PB_FILE_PERCENT.setValue(pc);
    }

    
    public void new_status(int code, String st)
    {
        last_code = code;
        if (last_status == null || last_status.compareTo(st) != 0)
        {
            last_status = st;
            if (code == ZipListener.ST_ERROR)
            {
                BT_ACTION.setText("Close");
                sb.append( "ERROR:\n");
            }

            if (code == ZipListener.ST_READY)
            {
                BT_ACTION.setText("Ready");
                BT_ACTION.setEnabled(true);
            }
            
            sb.append( st + "\n");
            String txt = sb.toString();
            TXTA_TERMINAL.setText( txt );
            // SET CARET TO END OF TEXT -> SCROLL
            TXTA_TERMINAL.setCaretPosition(txt.length());
        }
    }    
    public void add_description( String txt )
    {
        String new_text = TXTA_DESCRIPTION.getText();
        if ( new_text.length() > 0)
             new_text += "\n";
       if (txt != null)
             new_text += txt;
        
        TXTA_DESCRIPTION.setText(  new_text);
    }
    public void set_description(String new_text)
    {
        TXTA_DESCRIPTION.setText(  new_text);
    }

    
    public void actionPerformed(ActionEvent e)
    {
        auto_close_cnt--;
        BT_ACTION.setText("Ready (" + auto_close_cnt + ")");
        if (auto_close_cnt <= 0 && isVisible())
        {
            setVisible(false);
            finished = true;
        }  
    }
    
}
