package home.shared.hibernate;
// Generated 09.07.2009 10:42:43 by Hibernate Tools 3.2.1.GA



/**
 * Proxy generated by hbm2java
 */
public class Backup  implements java.io.Serializable {


     private int id;
     private DiskArchive diskArchive;
     private Mandant mandant;
     private String agentip;
     private String agentpath;
     private Integer agentport;
     private String schedenable;
     private String schedtime;
     private Integer cycleval;
     private String  cycleunit;
     private String  validfrom;
     private String flags;

    public Backup() {
    }

	
    public Backup(int id) {
        this.id = id;
    }

    public Backup( int id, DiskArchive diskArchive, Mandant mandant, String agentip, String agentpath, Integer agentport, String schedenable, String schedtime, Integer cycleval, String cycleunit, String validfrom, String flags )
    {
        this.id = id;
        this.diskArchive = diskArchive;
        this.mandant = mandant;
        this.agentip = agentip;
        this.agentpath = agentpath;
        this.agentport = agentport;
        this.schedenable = schedenable;
        this.schedtime = schedtime;
        this.cycleval = cycleval;
        this.cycleunit = cycleunit;
        this.validfrom = validfrom;
        this.flags = flags;
    }

    public Backup( Backup b )
    {
        this.id = b.id;
        this.diskArchive = b.diskArchive;
        this.mandant = b.mandant;
        this.agentip = b.agentip;
        this.agentpath = b.agentpath;
        this.agentport = b.agentport;
        this.schedenable = b.schedenable;
        this.schedtime = b.schedtime;
        this.cycleval = b.cycleval;
        this.cycleunit = b.cycleunit;
        this.validfrom = b.validfrom;
        this.flags = b.flags;
    }


    public String getAgentpath()
    {
        return agentpath;
    }

    public void setAgentpath( String agentpath )
    {
        this.agentpath = agentpath;
    }


    public String getAgentip()
    {
        return agentip;
    }

    public void setAgentip( String agentip )
    {
        this.agentip = agentip;
    }

    public Integer getAgentport()
    {
        return agentport;
    }

    public void setAgentport( Integer agentport )
    {
        this.agentport = agentport;
    }

    public String getCycleunit()
    {
        return cycleunit;
    }

    public void setCycleunit( String cycleunit )
    {
        this.cycleunit = cycleunit;
    }

    public Integer getCycleval()
    {
        return cycleval;
    }

    public void setCycleval( Integer cycleval )
    {
        this.cycleval = cycleval;
    }

    public String getFlags()
    {
        return flags;
    }

    public void setFlags( String flags )
    {
        this.flags = flags;
    }

    public String getSchedenable()
    {
        return schedenable;
    }

    public void setSchedenable( String schedenable )
    {
        this.schedenable = schedenable;
    }

    public String getSchedtime()
    {
        return schedtime;
    }

    public void setSchedtime( String schedtime )
    {
        this.schedtime = schedtime;
    }


   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public DiskArchive getDiskArchive() {
        return this.diskArchive;
    }
    
    public void setDiskArchive(DiskArchive diskArchive) {
        this.diskArchive = diskArchive;
    }
    public Mandant getMandant() {
        return this.mandant;
    }
    
    public void setMandant(Mandant mandant) {
        this.mandant = mandant;
    }

    public void setValidfrom( String validfrom )
    {
        this.validfrom = validfrom;
    }

    public String getValidfrom()
    {
        return validfrom;
    }
}


