package home.shared.hibernate;
// Generated 09.07.2009 10:42:43 by Hibernate Tools 3.2.1.GA

/**
 * MailHeaderVariable generated by hbm2java
 */
public class MailHeaderVariable  implements java.io.Serializable {


     private int id;
     private String varName;
     private Mandant mandant;
     private int flags;


    public MailHeaderVariable() {
    }

	
    public MailHeaderVariable(int id) {
        this.id = id;
    }

    public MailHeaderVariable( int id, String varName, Mandant mandant, int flags )
    {
        this.id = id;
        this.varName = varName;
        this.mandant = mandant;
        this.flags = flags;
    }

    public MailHeaderVariable( MailHeaderVariable hmv )
    {
        this.id = hmv.id;
        this.varName = hmv.varName;
        this.mandant = hmv.mandant;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getVarName() {
        return this.varName;
    }
    
    public void setVarName(String varName) {
        this.varName = varName;
    }
    public Mandant getMandant() {
        return this.mandant;
    }

    public void setMandant(Mandant mandant) {
        this.mandant = mandant;
    }

    public int getFlags()
    {
        return flags;
    }

    public void setFlags( int flags )
    {
        this.flags = flags;
    }






}


