package home.shared.hibernate;
// Generated 09.07.2009 10:42:43 by Hibernate Tools 3.2.1.GA




/**
 * AccountConnector generated by hbm2java
 */
public class MailAddress  implements java.io.Serializable {


     private int id;
     Mandant mandant;
     private String email;
     private int flags;


    public MailAddress() {
    }

	
    public MailAddress(int id) {
        this.id = id;
    }

    public MailAddress( int id, Mandant mandant, String email, int flags )
    {
        this.id = id;
        this.mandant = mandant;
        this.email = email;
        this.flags = flags;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mandant getMandant() {
        return this.mandant;
    }
    
    public void setMandant(Mandant mandant) {
        this.mandant = mandant;
    }

    /**
     * @return the flags
     */
    public int getFlags()
    {
        return flags;
    }

    /**
     * @param flags the flags to set
     */
    public void setFlags( int flags )
    {
        this.flags = flags;
    }

    /**
     * @return the email
     */
    public String getEmail()
    {
        return email;
    }

    /**
     * @param email the email to set
     */
    public void setEmail( String email )
    {
        this.email = email;
    }



}


