package home.shared.hibernate;
// Generated 09.07.2009 10:42:43 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Mandant generated by hbm2java
 */
public class Mandant  implements java.io.Serializable {


     private int id;
     private String name;
     private String license;
     private String password;
     private String loginname;
     private String flags;
     private int imap_port;
     private String imap_host;
     private int smtp_port;
     private String smtp_host;
     private String smtp_user;
     private String smtp_pwd;
     private String notificationlist;
     private String mailfrom;
     private int smtp_flags;
     
     private Set<Hotfolder> hotfolders = new HashSet<Hotfolder>(0);
     private Set<ImapFetcher> imapFetchers = new HashSet<ImapFetcher>(0);
     private Set<Role> roles = new HashSet<Role>(0);
     private Set<Milter> milters = new HashSet<Milter>(0);
     private Set<Proxy> proxies = new HashSet<Proxy>(0);
     private Set<DiskArchive> diskArchives = new HashSet<DiskArchive>(0);
     private Set<AccountConnector> accountConnectors = new HashSet<AccountConnector>(0);
     private Set<MailHeaderVariable> mailHeaderVariable = new HashSet<MailHeaderVariable>(0);
     private Set<MailUser> mailusers = new HashSet<MailUser>(0);
     private Set<Backup> backups = new HashSet<Backup>(0);

    public Mandant()
    {
    }

	
    public Mandant(int id, String name, String license, String password, String loginname, String flags, int imap_port, String imap_host,
            int smtp_port, String smtp_host, String smtp_user, String smtp_pwd, int smtp_flags) {
        this.id = id;
        this.name = name;
        this.license = license;
        this.password = password;
        this.loginname = loginname;
        this.flags = flags;
        this.imap_port = imap_port;
        this.imap_host = imap_host;
        this.smtp_port = smtp_port;
        this.smtp_host = smtp_host;
        this.smtp_user = smtp_user;
        this.smtp_pwd = smtp_pwd;
        this.smtp_flags = smtp_flags;
    }
    public Mandant(int id, String name, String license, String password, String loginname, String flags, int imap_port, String imap_host, 
                int smtp_port, String smtp_host, String smtp_user, String smtp_pwd, int smtp_flags,
                Set<Hotfolder> hotfolders,
                Set<ImapFetcher> imapFetchers, Set<Role> roles, Set<Milter> milters, Set<Proxy> proxies, Set<DiskArchive> diskArchives,
                Set<AccountConnector> accountConnectors, Set<MailHeaderVariable> mailHeaderVariable, Set<MailUser> mailusers,
                Set<Backup> backups)
    {
       this.id = id;
       this.name = name;
       this.license = license;
       this.password = password;
       this.loginname = loginname;
       this.flags = flags;
       this.imap_port = imap_port;
       this.imap_host = imap_host;
       this.hotfolders = hotfolders;
       this.imapFetchers = imapFetchers;
       this.roles = roles;
       this.milters = milters;
       this.proxies = proxies;
       this.diskArchives = diskArchives;
       this.accountConnectors = accountConnectors;
       this.mailHeaderVariable = mailHeaderVariable;
       this.mailusers = mailusers;
       this.backups = backups;
        this.smtp_port = smtp_port;
        this.smtp_host = smtp_host;
        this.smtp_user = smtp_user;
        this.smtp_pwd = smtp_pwd;
        this.smtp_flags = smtp_flags;
    }


    public Mandant( Mandant m )
    {
       this.id = m.id;
       this.name = m.name;
       this.license = m.license;
       this.password = m.password;
       this.loginname = m.loginname;
       this.flags = m.flags;
       this.imap_port = m.imap_port;
       this.imap_host = m.imap_host;
       this.hotfolders = m.hotfolders;
       this.imapFetchers = m.imapFetchers;
       this.roles = m.roles;
       this.milters = m.milters;
       this.proxies = m.proxies;
       this.diskArchives = m.diskArchives;
       this.accountConnectors = m.accountConnectors;
       this.mailHeaderVariable = m.mailHeaderVariable;
       this.mailusers = m.mailusers;
       this.backups = m.backups;
        this.smtp_port = m.smtp_port;
        this.smtp_host = m.smtp_host;
        this.smtp_user = m.smtp_user;
        this.smtp_pwd = m.smtp_pwd;
        this.mailfrom = m.mailfrom;
        this.notificationlist = m.notificationlist;
        this.smtp_flags = m.smtp_flags;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLicense() {
        return this.license;
    }
    
    public void setLicense(String license) {
        this.license = license;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getLoginname() {
        return this.loginname;
    }
    
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }
    public String getFlags() {
        return this.flags;
    }
    
    public void setFlags(String flags) {
        this.flags = flags;
    }
    public Set<Hotfolder> getHotfolders() {
        return this.hotfolders;
    }
    
    public void setHotfolders(Set<Hotfolder> hotfolders) {
        this.hotfolders = hotfolders;
    }
    public Set<ImapFetcher> getImapFetchers() {
        return this.imapFetchers;
    }
    
    public void setImapFetchers(Set<ImapFetcher> imapFetchers) {
        this.imapFetchers = imapFetchers;
    }
    public Set<Role> getRoles() {
        return this.roles;
    }
    
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }
    public Set<Milter> getMilters() {
        return this.milters;
    }
    
    public void setMilters(Set<Milter> milters) {
        this.milters = milters;
    }
    public Set<Proxy> getProxies() {
        return this.proxies;
    }
    
    public void setProxies(Set<Proxy> proxies) {
        this.proxies = proxies;
    }
    public Set<DiskArchive> getDiskArchives() {
        return this.diskArchives;
    }
    
    public void setDiskArchives(Set<DiskArchive> diskArchives) {
        this.diskArchives = diskArchives;
    }
    public Set<AccountConnector> getAccountConnectors() {
        return this.accountConnectors;
    }

    public void setAccountConnectors(Set<AccountConnector> accountConnectors) {
        this.accountConnectors = accountConnectors;
    }

    public Set<MailHeaderVariable>  getMailHeaderVariable() {
        return this.mailHeaderVariable;
    }

    public void setMailHeaderVariable(Set<MailHeaderVariable> mailHeaderVariable) {
        this.mailHeaderVariable = mailHeaderVariable;
    }

    /**
     * @return the imap_port
     */
    public int getImap_port()
    {
        return imap_port;
    }

    /**
     * @param imap_port the imap_port to set
     */
    public void setImap_port( int imap_port )
    {
        this.imap_port = imap_port;
    }

    /**
     * @return the imap_host
     */
    public String getImap_host()
    {
        return imap_host;
    }

    /**
     * @param imap_host the imap_host to set
     */
    public void setImap_host( String imap_host )
    {
        this.imap_host = imap_host;
    }

    /**
     * @return the mailusers
     */
    public Set<MailUser> getMailusers()
    {
        return mailusers;
    }

    /**
     * @param mailusers the mailusers to set
     */
    public void setMailusers( Set<MailUser> mailusers )
    {
        this.mailusers = mailusers;
    }

    /**
     * @return the smtp_port
     */
    public int getSmtp_port()
    {
        return smtp_port;
    }

    /**
     * @param smtp_port the smtp_port to set
     */
    public void setSmtp_port( int smtp_port )
    {
        this.smtp_port = smtp_port;
    }

    /**
     * @return the smtp_host
     */
    public String getSmtp_host()
    {
        return smtp_host;
    }

    /**
     * @param smtp_host the smtp_host to set
     */
    public void setSmtp_host( String smtp_host )
    {
        this.smtp_host = smtp_host;
    }

    /**
     * @return the smtp_user
     */
    public String getSmtp_user()
    {
        return smtp_user;
    }

    /**
     * @param smtp_user the smtp_user to set
     */
    public void setSmtp_user( String smtp_user )
    {
        this.smtp_user = smtp_user;
    }

    /**
     * @return the smtp_pwd
     */
    public String getSmtp_pwd()
    {
        return smtp_pwd;
    }

    /**
     * @param smtp_pwd the smtp_pwd to set
     */
    public void setSmtp_pwd( String smtp_pwd )
    {
        this.smtp_pwd = smtp_pwd;
    }

    /**
     * @return the smtp_flags
     */
    public int getSmtp_flags()
    {
        return smtp_flags;
    }

    /**
     * @param smtp_flags the smtp_flags to set
     */
    public void setSmtp_flags( int smtp_flags )
    {
        this.smtp_flags = smtp_flags;
    }

    public String getNotificationlist()
    {
        return notificationlist;
    }

    public String getMailfrom()
    {
        return mailfrom;
    }

    public void setNotificationlist( String notificationlist )
    {
        this.notificationlist = notificationlist;
    }

    public void setMailfrom( String mailfrom )
    {
        this.mailfrom = mailfrom;
    }

    public Set<Backup> getBackups()
    {
        return backups;
    }

    public void setBackups( Set<Backup> backups )
    {
        this.backups = backups;
    }




}


