package home.shared.hibernate;
// Generated 09.07.2009 10:42:43 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;




/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private int id;
     private Mandant mandant;
     private String name;
     private String opts;
     private String accountmatch;
     private Integer license;
     private String flags;
     private AccountConnector accountConnector;
     private Set<RoleOption> roleOptions = new HashSet<RoleOption>(0);

    public Role() {
    }

	
    public Role(int id) {
        this.id = id;
    }
    public Role(int id, Mandant mandant, String name, String opts, String acm, Integer license, String flags, AccountConnector ac, Set<RoleOption> roleOptions) {
       this.id = id;
       this.mandant = mandant;
       this.name = name;
       this.license = license;
       this.opts = opts;
       accountmatch = acm;
       this.flags = flags;
       this.accountConnector = ac;
       this.roleOptions = roleOptions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Mandant getMandant() {
        return this.mandant;
    }
    
    public void setMandant(Mandant mandant) {
        this.mandant = mandant;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getLicense() {
        return this.license;
    }
    
    public void setLicense(Integer license) {
        this.license = license;
    }
    public String getOpts() {
        return this.opts;
    }

    public void setOpts(String opts) {
        this.opts = opts;
    }

    public String getAccountmatch() {
        return this.accountmatch;
    }

    public void setAccountmatch(String ac) {
        this.accountmatch = ac;
    }

    public String getFlags() {
        return this.flags;
    }

    public void setFlags(String flags) {
        this.flags = flags;
    }

    public AccountConnector getAccountConnector() {
        return this.accountConnector;
    }

    public void setAccountConnector(AccountConnector ac) {
        this.accountConnector = ac;
    }

    public Set<RoleOption> getRoleOptions() {
        return this.roleOptions;
    }

    public void setRoleOptions(Set<RoleOption> roleOptions) {
        this.roleOptions = roleOptions;
    }

}


