package home.shared.hibernate;
// Generated 09.07.2009 10:42:43 by Hibernate Tools 3.2.1.GA



/**
 * HotfolderExclude generated by hbm2java
 */
public class RoleOption  implements java.io.Serializable {


     private int id;
     private Role role;
     private String token;
     private int flags;


    public RoleOption() {
    }

	
    public RoleOption(int id) {
        this.id = id;
    }
    public RoleOption(int id, Role r, String token, int flags) {
       this.id = id;
       this.role = r;
       this.token = token;
       this.flags = flags;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }
    public String getToken() {
        return this.token;
    }
    
    public void setToken(String token) {
        this.token = token;
    }
    public int getFlags() {
        return this.flags;
    }
    
    public void setFlags(int flags) {
        this.flags = flags;
    }




}


